engines:
  pep8:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        - python:

  fixme:
    enabled: true

  markdownlint:
    enabled: true

ratings:
  paths:
    - "**.md"
    - "**.py"
