version: "3"
services:

  beat:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ".:/code"
    depends_on:
      - broker

  flower:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ".:/code"
    depends_on:
      - broker
    ports:
      - 5555:5555
    command: ["celery", "-A", "my_internet_speed", "flower"]

  dashboard:
    build:
      context: dashboard/
    depends_on:
      - api
    volumes:
      - "./dashboard:/code"
    ports:
      - 3000:3000

  api:
    env_file:
      - .env
    image: postgrest/postgrest
    ports:
      - 3001:3000

  db:
    image: postgres:11.2
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql

  broker:
    image: redis:5.0.3
